title:  CyberSciTech/PICom/DASC/CDBCom 2024
description: CyberSciTech 2024



baseurl: /2024
color-scheme: "#1B365D" # the scheme can be any HEX code like "#00aa55"
dasc-scheme: "#88aef7"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
